Architecture changes
AndrewPyatunin/Task_Scheduler pull request #1
Opened 2023-12-06 20:10 UTC by AndrewPyatunin

Too many changes, see in commits

2023-12-07 14:58 UTC, sharon-makaron requested changes

2023-12-07 14:58 UTC, sharon-makaron commented on app/build.gradle
> +    annotationProcessor("androidx.room:room-compiler:2.5.2")
А почему не kapt?

2023-12-07 14:58 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/BoardDb.kt
> +data class BoardDb(
Энтити именуем по правилу `NameEntity`, то есть `BoardEntity`

2023-12-07 14:58 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/Database.kt
> +    companion object {
По котлин-конвенциям лучше делать всегда пустую строку между именем сущности и ее контентом, можно настроить себе по `cmd+option+L (ctrl+alt+L)`

2023-12-07 14:58 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/Database.kt
> +        fun getInstance(application: Application): TaskDatabase {
Аналогично стоит делать пустую строку между переменными и методами класса

2023-12-07 14:58 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/ListOfNotesDb.kt
> +) {
Лишние скобки

2023-12-07 14:58 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/LocalDataSource.kt
> +interface LocalDataSource {
Очень похоже, что с этим интерфейсом невозможно будет работать: как его расширять? Если я добавлю сюда еще один метод, я захочу отрезать себе руки. Я думаю, что есть смысл подумать о том, как можно его разнести (можно завести задачу и сюда ебануть todo)

`todo TASK-123 segregate this into parts`

2023-12-07 14:58 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/MapperForBoardAndBoardDb.kt
> +class MapperForBoardAndBoardDb {
1. Плохое название. Мапперы обычно имеют названия вида `WhatToWhatMapper`, рекомендую через `Refactor -> Rename` поменять все названия подобных классов на понятные
2. Что-то маппер слишком жирный. Обычно их задача – замапить одно в другое, чтобы изи можно было покрыть юнитами. Если становится много методов в маппере, стоит подумать о том, чтобы создавать либо несколько мапперов, либо пересмотреть подход к маппингу

Еще рекомендую закрывать все мапперы интерфейсом, потому что так легче будет тестить классы, зависящие от этих мапперов. Я когда-то говорил, что в целом незазорно создать что-то типа

```kotlin
interface Mapper<I, T> {
    fun map(from: I): T
}
```

И наследовать его, подставляя нужные типы. В таком случае не получится просто так взять и запихнуть в маппер кучу методов, раз есть контракт, а во-вторых, будет проще работать с маппингом, так как у тебя будет один входящий тип, один исходящий. **Из минусов**: будет дохера имплементаций одного интерфейса, что в большом проекте уже плохо

2023-12-07 14:58 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/TaskDatabaseDao.kt
> +//    @Query("SELECT * FROM users WHERE email = :email")
Комментарии лучше не дежать в кодовой базе, у тебя же есть git

2023-12-07 14:58 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/TaskDatabaseDao.kt
> +
Лишняя пустая строка

2023-12-07 14:58 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/UserDb.kt
> +) {
Лишние пустые скобки (пробегись по всем классам и удали их)

2023-12-07 14:58 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/domain/TaskRepository.kt
> +interface TaskRepository {
Аналогичная ситуация с этим репозиторием. Его нужно разносить, и я понимаю, что сделать это сразу сложно, надо подумать и отдельной задачей сделать разделение. Поставь тут тудушку тоже

2023-12-07 14:58 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/presentation/boardlist/BoardListFragment.kt
> +            if (it!=null) {
Почитай [конвенции Kotlin](https://kotlinlang.org/docs/coding-conventions.html): не стоит лепить символы друг к другу, лучше всегда оставлять пробелы, такие штуки решаются через `cmd + option + L` или через использование статического анализатора

2023-12-07 14:58 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/presentation/boardlist/BoardListFragment.kt
> +        viewModel.firebaseUser.observe(viewLifecycleOwner, Observer {
Вроде как можно просто

```kotlin
viewModel.firebaseUser.observe(viewLifecycleOwner, {
```

2023-12-07 14:58 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/presentation/boardlist/BoardListViewModel.kt
> +    val repository = TaskRepositoryImpl()
Вот оно, отсутствие DI :)

2023-12-07 14:58 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/presentation/boardlist/BoardListViewModel.kt
> +    private val _boardsLiveData by lazy {
`LAZY` по умолчанию потокобезопасный, можно сделать функцию в какой-то коммон-папке, которая будет вызвать внутри себя `lazy(NONE)`, и эту функцию юзать в проекте

И вопрос: зачем лейзи вообще?

2023-12-07 14:58 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/presentation/boardlist/BoardListViewModel.kt
> +        _boardsLiveData.removeObserver(observer)
Не понял этот мув, зачем тут обзервер?

2023-12-07 14:58 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/presentation/boardlist/BoardListViewModel.kt
> +                _boardList.value = list
Заменить на `boards.map { ... }`

2023-12-07 14:58 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/presentation/login/LoginFragment.kt
> +    var someProperty by Delegate<String>()
Это шо?

2023-12-07 14:58 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/presentation/login/LoginFragment.kt
> +                launchWelcomeFragment(it)
Можно

```kotlin
it?.let { ::launchWelcomeFragment }
```

2023-12-07 14:58 UTC, NikiZ97 commented on app/src/main/java/com/example/taskscheduler/presentation/newboard/NewBoardViewModel.kt
> +//        taskDatabase?.taskDatabaseDao()?.getUser(1)?.collect()
Все вот это надо разносить по функциям, невозможно читать

2023-12-07 14:58 UTC, NikiZ97 commented on app/src/main/java/com/example/taskscheduler/data/AuthenticationOfUser.kt
> +class AuthenticationOfUser(
`UserAuthentication`

2023-12-08 15:29 UTC, AndrewPyatunin commented on app/src/main/java/com/example/taskscheduler/data/MapperForBoardAndBoardDb.kt
> +class MapperForBoardAndBoardDb {
Это получается что-то типа такого c, кучей параметров однотипных?
TaskRepositoryImpl(
    private val userToUserEntityMapper: Mapper<User, UserEntity>,
    private val userEntityToUserMapper: Mapper<UserEntity, User>
    ...
)

2023-12-09 09:45 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/MapperForBoardAndBoardDb.kt
> +class MapperForBoardAndBoardDb {
Типа того, но можно делать мапперы, наследующиеся от интерфейса:

```kotlin
class SomeMapper : Mapper<User, UserEntity>
```

2023-12-09 10:21 UTC, sharon-makaron requested changes

2023-12-09 10:21 UTC, sharon-makaron commented on app/build.gradle
> +    implementation "androidx.lifecycle:lifecycle-livedata-ktx:2.6.1"
Есть хорошая практика выноса версий в отдельный блок типа `ext { ... }` или в отдельный файл, как удобнее. Можно в интернете посмотреть примеры, а тут задачку завести на рефактор билд-файлов. 

Преимущества: все версии будут в одном месте, при обновлении версий библиотек будет гораздо легче ориентироваться

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/TaskRepositoryImpl.kt
> +    private val auth = Firebase.auth
По идее все то, что из фаербейза достаем, можно в `init` обернуть, оно же по сути инициализируется тут

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/TaskRepositoryImpl.kt
> +    private val databaseBoardsReference = firebaseDatabase.getReference("Boards")
Все строковые константы лучше выносить в переменные, иначе потом пидется дублировать в других местах. Предлагаю или топ-левел, или компаньон, смотри, что удобнее

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/TaskRepositoryImpl.kt
> +                for (dataSnapshot in snapshot.children) {
Заменить на `forEach` или `map`

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/TaskRepositoryImpl.kt
> +                for (dataSnapshot in snapshot.children) {
Заменить на `map` или `forEach`

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/TaskRepositoryImpl.kt
> +    override fun createNewBoard(name: String, user: User, urlBackground: String, board: Board) =
Давай поделим функцию на несколько, лучше больше 30-40 строк одну функцию не делать, тяжело читать

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/TaskRepositoryImpl.kt
> +                        trySend(boardToDb)
Всё вот это вот легко делается через операторы на коллекциях: не надо создавать промежуточные коллекции, добавлять в них айтемы, можно сделать одну цепочку по сути (см. `map`, `forEach` и другие)

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/TaskRepositoryImpl.kt
> +    private fun getListsOfNotes(): List<ListOfNotesItem> {
У тебя приватные и оверрайд-функции перемешаны, лучше их разносить: сначала все оверрайды, потом все приватные

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/TaskRepositoryImpl.kt
> +            deleteList(list, board, false)
Как минимум, можно не делать эти `for`, а заменить на операторы: 

```kotlin
listsOfNotes.filter { it.id in board.listsOfNotesIds }
    .forEach { deleteList(...) }
```
**Правило такое**: хочешь написать фор, подумай о том, как это сделать менее многословно через операции над коллекциями

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/TaskRepositoryImpl.kt
> +                override fun onCancelled(error: DatabaseError) {
В пустых функциях можно писать просто: 

```kotlin
override fun onCancelled(error: DatabaseError) = Unit
```

У тебя же юнит юзается как объект, его возвращать можно

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/TaskRepositoryImpl.kt
> +
Пустые строки тоже не найс)

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/TaskRepositoryImpl.kt
> +    interface UrlCallback {
Почему интерфейс затерялся среди функций?)

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/TaskRepositoryImpl.kt
> +                it.exception?.let { exception ->
Вроде должно можно быть рефом сделать: `it.exception?.let(::throw)`, но не уверен, что можно сослаться на `throw`. Вообще лучше юзать рефы, где возможно, вместо лямбд

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/TaskRepositoryImpl.kt
> +                Toast.makeText(getApplication(), "${it.result}", Toast.LENGTH_SHORT).show()
Юай в дата-слое?)

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/TaskRepositoryImpl.kt
> +                        _success.value = "Приглашение успешно отправлено"
Такие штуки должны быть вынесены. Странно, что у тебя текстовка вообще в дата-слое застряла, тут же только данные

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/UserAuthentication.kt
> +            override fun onSuccess(p0: AuthResult?) {
Параметры бы тоже хорошо переименовывать, `p0` как-то не совсем удобно

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/UserAuthentication.kt
> +        awaitClose {
Это шо?

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/UserAuthentication.kt
> +        }.addOnFailureListener {
Это шо?

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/mappers/ListOfNotesEntityToListOfNotesItemMapper.kt
> +class ListOfNotesEntityToListOfNotesItemMapper : Mapper<ListOfNotesEntity, ListOfNotesItem> {
`NotesListEntityToNotesListItemMapper`

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/domain/UserAuthStateDomain.kt
> +
Лишняя пустая строка

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/domain/models/ListOfNotesItem.kt
> +data class ListOfNotesItem(
`NotesListItem`

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/domain/models/Note.kt
> +    Parcelable
Тут парселейбл убежал

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/domain/models/User.kt
> +
Пустая строка лишняя

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/domain/usecases/AddInviteUseCase.kt
> +class AddInviteUseCase {
Удали пустые юзкейсы, потом из гита достанешь

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/presentation/ForgotPasswordFragment.kt
> +                        context, "На ваш электронный адрес было отправлено письмо" +
Строки надо тащить из `strings.xml`

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/presentation/boardlist/BoardListFragment.kt
> +                    Glide.with(this@BoardListFragment).load(it.uri).centerCrop()
А тут разве не лайфсайкл оунера надо передавать в `with`?

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/presentation/boardlist/BoardListViewModel.kt
> +    fun getBoardsFlow(user: User) = getBoardsFlowUseCase.execute(user).onEach {
Тут что-то дофига пустых лямбд

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/presentation/boardlist/BoardListViewModel.kt
> +    val userFlow = (auth.currentUser?.uid ?: MyDatabaseConnection.userId)?.let {
Можно на реф заменить: `?.let(::getUserFlowFromRoomUseCase.execute)`

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/presentation/login/LoginFragment.kt
> +                                UserAuthState.Loading -> {
Опять пустые скобки, атата

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/presentation/newboard/NewBoardViewModel.kt
> +                Toast.makeText(context, "Произошла ошибка ${it.message}", Toast.LENGTH_SHORT).show()
Почему обновление юай залетело в презентейшн-слой?)

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/presentation/registration/RegistrationFragment.kt
> +                ChooseAvatarOptionFragment().newInstance()
Странная конструкция. Если создаешь объект через фабрику, то зачем тебе сначала его создавать, а потом фабрику вызывать? Дважды объект создается же

2023-12-09 10:21 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/presentation/registration/RegistrationFragment.kt
> +                    Toast.makeText(requireContext(), "Заполните все поля!", Toast.LENGTH_SHORT)
Вынеси все строки в `strings.xml`. Ты ведь знаешь для чего? Ты ведь знаешь?

2023-12-09 11:32 UTC, AndrewPyatunin commented on app/src/main/java/com/example/taskscheduler/data/TaskRepositoryImpl.kt
> +                it.exception?.let { exception ->
Мне как-то на лямбдах удобнее, спокойнее что ли, это обязательно?)

2023-12-09 11:32 UTC, AndrewPyatunin commented on app/src/main/java/com/example/taskscheduler/data/TaskRepositoryImpl.kt
> +                Toast.makeText(getApplication(), "${it.result}", Toast.LENGTH_SHORT).show()
Скидывал из viewModel без правок, бывает

2023-12-09 11:33 UTC, AndrewPyatunin commented on app/src/main/java/com/example/taskscheduler/data/TaskRepositoryImpl.kt
> +                Toast.makeText(getApplication(), "${it.result}", Toast.LENGTH_SHORT).show()
> Юай в дата-слое?)

Скидывал из viewModel без правок, бывает

2023-12-09 11:33 UTC, AndrewPyatunin commented on app/src/main/java/com/example/taskscheduler/data/TaskRepositoryImpl.kt
> +                it.exception?.let { exception ->
> Вроде должно можно быть рефом сделать: `it.exception?.let(::throw)`, но не уверен, что можно сослаться на `throw`. Вообще лучше юзать рефы, где возможно, вместо лямбд

Мне как-то на лямбдах удобнее, спокойнее что ли, это обязательно?)

2023-12-09 11:42 UTC, AndrewPyatunin commented on app/src/main/java/com/example/taskscheduler/presentation/registration/RegistrationFragment.kt
> +                ChooseAvatarOptionFragment().newInstance()
> Странная конструкция. Если создаешь объект через фабрику, то зачем тебе сначала его создавать, а потом фабрику вызывать? Дважды объект создается же

Да надо править, закомменчено это было раньше, похоже не зря) Edit: companion object не хватало в ChooseAvatarOptionFragment - поправил

2023-12-09 11:55 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/TaskRepositoryImpl.kt
> +                it.exception?.let { exception ->
Необязательно, но более лаконично

2023-12-09 16:44 UTC, AndrewPyatunin commented on app/src/main/java/com/example/taskscheduler/data/TaskRepositoryImpl.kt
> +                        trySend(boardToDb)
> Всё вот это вот легко делается через операторы на коллекциях: не надо создавать промежуточные коллекции, добавлять в них айтемы, можно сделать одну цепочку по сути (см. `map`, `forEach` и другие)

Уже самому сложно во всем этом разбираться))

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/database/BoardDao.kt
> +    suspend fun addBoardList(boards: List<BoardEntity>)
Лучше 
```suggestion
    suspend fun addBoards(boards: List<BoardEntity>)
```

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/repos/NoteRepositoryImpl.kt
> +    ) = suspendCancellableCoroutine { continuation ->
```suggestion
    ) = suspendCancellableCoroutine { _ ->
```
Похоже continuation не юзается

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/repos/NotesListRepositoryImpl.kt
> +                val listOfLists = ArrayList<NotesListItem>()
1. Лучше создавать фабриками через `mutableListOf()`, например
2. Лучше вообще не создавать руками такие коллекции. Тут можно заюзать `map`

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/repos/NotesListRepositoryImpl.kt
> +                scope.launch(Dispatchers.IO) {
А зачем тут сначала на скоупе ИО, потом внутри свитчится контекст снова в ИО?

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/ChooseAvatarOptionFragment.kt
> +                .setPositiveButton(
На подумать: что будет, если такой диалог будет открыт, но ты сменишь, например, тему на телефоне, а потом тапнешь какой-нибудь экшн в диалоге? Как пофиксить поведение?

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/entities/BoardEntity.kt
> +    val listOfNotesIds: Map<String, Boolean>
```suggestion
    val notesIds: Map<String, Boolean>
```

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/entities/CheckNoteEntity.kt
> +data class CheckNoteEntity (
Лишний пробел

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/entities/Converters.kt
> +class Converters {
Минор: я бы назвал что-нибудь `RoomTypeConverters`, потому что в проекте может появиться миллион конвертеров и тебе придется править название у этого при создании нового

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/mappers/NoteToNoteEntityMapper.kt
> +
Лишняя строка

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/mappers/NotesListEntityToNotesListItemMapper.kt
> +
Лишняя строка

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/mappers/NotesListItemToNotesListEntityMapper.kt
> +
Лишняя строка. Просмотри файлы на наличие лигних строк

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/repos/BoardRepositoryImpl.kt
> +    private val boardDataSource = BoardDataSourceImpl(boardDao)
Хуя се DI-контейнер

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/repos/BoardRepositoryImpl.kt
> +            list.map {
Тут можно в референс свернуть

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/repos/BoardRepositoryImpl.kt
> +            deleteList(it, board, false)
Для таких буленов лучше делать named параметр

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/repos/BoardRepositoryImpl.kt
> +        if (isList) updateBoard(
Странная конструкция. Либо скобки поставь, либо в одну строку ебани

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/repos/BoardRepositoryImpl.kt
> +            boardToBoardEntityMapper.map(it)
Тут тоже референс можно сделать

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/repos/BoardRepositoryImpl.kt
> +    override suspend fun createNewBoard(
Очень сложно читать функцию, глаза слезятся, можешь подрефачить?

Из очевидных фиксов:

1. почему-то поилетает в параметр `board`, у которого сравнивается айдишник на пустоту, мб это вынести? Разнести в целом этот код на части
2. Какие-то локальные переменные в функции создаются, может можно этого избежать?

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/repos/InviteRepositoryImpl.kt
> +        clearInviteInDatabase(user.copy(boards = (user.boards as MutableMap).apply {
А смысл копировать, чтобы кастить мапу в мутабельную? Сделай копию, в которую положи значение по новому айдишнику

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/repos/InviteRepositoryImpl.kt
> +        clearInviteInDatabase(user, invite)
Бесполезная прокси-функция, если она только тут юзается, рекомендую код из нее сюда заинлайнить

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/repos/InviteRepositoryImpl.kt
> +                            if (continuation.isActive) {
А что, если нет?

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/repos/InviteRepositoryImpl.kt
> +            inviteToInviteEntityMapper.map(invite)
Опять реф можно, лучше его юзать, если есть возможность

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/repos/UserAuthentication.kt
> +    fun login(email: String, password: String, auth: FirebaseAuth) {
Это что?

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/repos/UserRepositoryImpl.kt
> +    dao: UserDao
В одну строку все влезет

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/data/repos/UserRepositoryImpl.kt
> +        if (description != "") {
```suggestion
        if (description.isNotEmpty()) {
```

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/presentation/ForgotPasswordFragment.kt
>          email = args.email
Кажется, что тоже можно заинлайнить

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/presentation/MainActivity.kt
> +    private var pref: SharedPreferences? = null
А не хочешь обертку над префами написать?

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/presentation/boardlist/BoardListViewModel.kt
> +                Log.d("DataUpdate", "New data collected: $it") // Log the new data
Очень много логов в проекте. В идеале не срать логами в репозитории, тк не ты один потенциально юзаешь этот код. Либо сделать какой-то логгер, который бы в разные системы мог логгировать (например, в фаербейз или какую-то твою личную систему)

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/presentation/boardlist/BoardListViewModelFactory.kt
> +class BoardListViewModelFactory(val application: Application): ViewModelProvider.Factory {
```suggestion
class BoardListViewModelFactory(private val application: Application): ViewModelProvider.Factory {
```
?

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/presentation/boardupdated/InnerBoardFragment.kt
> +            newList = newList.sortedWith { ln, rn ->
Омг. Может вынести в компаратор отдельный, чтобы хоть было более-менее понятен его смысл?

2024-01-16 13:56 UTC, sharon-makaron commented on app/src/main/java/com/example/taskscheduler/presentation/boardupdated/InnerBoardFragment.kt
> +            recyclerView.visibility = View.VISIBLE
А смысл? Сделай сразу видимым в разметке

2024-02-13 17:49 UTC, merged